Rename `toBeAccessible` to `toHaveNoAxeViolations`
Widen/expect-axe-playwright pull request #24
Opened 2022-08-11 09:35 UTC by gabalafou

This pull request renames the matcher because it is potentially misleading and includes a new section in the readme explaining why. To preserve backwards compatibility, it still supports the old matcher name, but prints a deprecation notice to the console.

2022-08-11 09:45 UTC, gabalafou reviewed
done self-reviewing

2022-08-12 14:59 UTC, mskelton commented
While I understand the reason why, the use case for testing a generated report is small, and I don't want to change the matcher name for the majority use case which is testing actual page elements.  My recommendation would be to do this manually in your code like so:

```js
expect.extend({ toHaveNoAxeViolations: matchers.toBeAccessible })
```

2022-08-15 14:16 UTC, mskelton commented
Just occurred to me that it may be simpler and cleaner to add another matcher to this library `toHaveNoAxeViolations` which accepts an axe results object to keep the two matchers totally separate for each use case.

2022-09-08 03:23 UTC, gabalafou commented
I fear I may not be communicating effectively because I'm doing too many things at once.

This PR isn't really about issue #21. It's related to that issue only tangentially.

The real issue here is described in the changes I made to the repo's readme via this PR. I would ask that you please look at the files changed in this PR and read what I added to the readme if you haven't yet.

I'm afraid that as a developer in the accessibility space, I have too often encountered other developers who think that accessibility is some kind of binary—as if you could take a page or an app and say yes, it's accessible. But in this respect, accessibility is much more like security. You wouldn't take a website, make it pass a bunch of security checks on it, and then say, yes, it's secure. In the same way, it's foolish to run a bunch of accessibility checks on a site, and then if all of them pass, to say, yes, it's accessible. That's my concern with the dev-facing API of this library, i.e., `expect(page).toBeAccessible()`. It re-enforces this already pervasive, completely erroneous notion in the minds of developers that you can ever accurately call something "accessible." You can't, not anymore than you can call something secure. 

If I thought that most developers "get it" and it were only a tiny minority that have these mistaken assumptions, then I wouldn't think this were a big deal. But based on my and my colleagues' experiences, I don't think that's the case. 

And if this didn't have the potential to negatively impact people who are already marginalized by society, then I could overlook it. But that is also not the case.

Ultimately, it's your decision to make, but I'm adding this comment because it wasn't clear to me from your previous comments whether I had effectively communicated what's really motivating this pull request. Thank you for listening and giving your time. :)

2022-09-08 13:41 UTC, mskelton commented
Thanks for the explanation, I understand now why you want to rename the matcher and it makes good sense.  I thought previously it was more to encapsulate the ability to pass a results object, so I now understand better your reason for this change.

I'm good with this change, but honestly I'd prefer to just make it a major change rather than deprecating the old matcher.  That way it's just one and done and we can get rid of the deprecated code and make that text you added front and center in the README like jest-axe has.

Does that sound reasonable?

2022-09-08 22:33 UTC, gabalafou commented
I so appreciate you being open to this change. 😊

If I understand you correctly, you're suggesting that I delete the `toBeAccessible` matcher and bump the version from 2 to 3, is that right?

2022-09-09 13:38 UTC, mskelton commented
> If I understand you correctly, you're suggesting that I delete the toBeAccessible matcher and bump the version from 2 to 3, is that right?

Yep, the version management is using changesets.  So you'll need to add a changeset with a major version bump.  The comment from the changeset bot should explain how that works.

2022-09-09 13:39 UTC, mskelton commented
Also, my coworker mentioned that perhaps we could find a better name.  `toNotHaveAxeViolations` is pretty verbose, and if combined with `not` then it's a double negative.  Could we use a name like `toPassAxe` or something similar?

2022-09-09 22:09 UTC, gabalafou commented
Haha I had the exact same thought regarding the double the negative. I then started imagining what the API might look like if it were a spellchecker, maybe something like:

```js
expect(doc).toPassSpellchecker()

const results = runSpellchecker(doc)
expect(results).toPassSpellchecker()
```

So I think `toPassAxe` makes sense to me.

2022-09-27 13:36 UTC, mskelton requested changes
The changelog should not be manually modified.  Please follow the instructions here to add a changeset:

https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md#i-am-in-a-single-package-repository

2022-09-27 13:36 UTC, mskelton commented on global.d.ts
>     * Verifies that the page, frame, or locator is accessible.
```suggestion
   * Verifies that the page, frame, or locator passes Axe tests.
```

2022-09-27 13:36 UTC, mskelton commented on package.json
> +  "version": "3.0.0",
The version will be bumped by changesets, please revert this change.

2022-09-27 17:35 UTC, mskelton approved these changes

2022-09-27 20:46 UTC, mskelton commented
Looks to be some Prettier errors

2022-09-27 20:52 UTC, merged